import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'

const html = await readFile('index.html', 'utf8')
const app = await readFile('app.js', 'utf8')
const onboarding = await readFile('onboarding.js', 'utf8')
const ai = await readFile('ai.js', 'utf8')
const gateway = await readFile('lib/ai-gateway.js', 'utf8')
const providersApi = await readFile('api/providers.js', 'utf8')
const inquiryApi = await readFile('api/inquiry.js', 'utf8')
const manifest = JSON.parse(await readFile('manifest.webmanifest', 'utf8'))
const worker = await readFile('sw.js', 'utf8')

assert.ok(html.includes('Socratic Kernel'))
assert.ok(html.includes('app.js'))
assert.ok(html.includes('onboarding.js'))
assert.ok(html.includes('ai.js'))
assert.ok(html.includes('ai.css'))
assert.ok(html.includes('data-route="models"'))
assert.ok(html.includes('manifest.webmanifest'))
assert.ok(app.includes('AI 使用审计'))
assert.ok(app.includes('判断外包'))
assert.ok(app.includes('delete-current'))
assert.ok(app.includes('serviceWorker'))
assert.ok(onboarding.includes('First inquiry'))
assert.ok(onboarding.includes('data-onboarding-example'))
assert.ok(onboarding.includes("form.elements.challenge.value = '1'"))
assert.ok(onboarding.includes('localStorage'))
assert.ok(!onboarding.includes('fetch('))
assert.ok(ai.includes('/api/providers'))
assert.ok(ai.includes('/api/inquiry'))
assert.ok(ai.includes('本地规则'))
assert.ok(ai.includes('AI 增强'))
assert.ok(ai.includes('供应商 API Key'))
assert.ok(!ai.includes('OPENAI_API_KEY'))
assert.ok(!ai.includes('ANTHROPIC_API_KEY'))
assert.ok(gateway.includes('OPENAI_API_KEY'))
assert.ok(gateway.includes('ANTHROPIC_API_KEY'))
assert.ok(gateway.includes('GEMINI_API_KEY'))
assert.ok(gateway.includes('DEEPSEEK_API_KEY'))
assert.ok(gateway.includes('DASHSCOPE_API_KEY'))
assert.ok(gateway.includes('MOONSHOT_API_KEY'))
assert.ok(gateway.includes('XAI_API_KEY'))
assert.ok(providersApi.includes('listEnabledProviders'))
assert.ok(inquiryApi.includes('requireGatewayToken'))
assert.ok(!html.includes('src/main.tsx'))
assert.equal(manifest.short_name, '内核')
assert.equal(manifest.display, 'standalone')
assert.ok(worker.includes('socratic-kernel-v4'))
assert.ok(worker.includes('ai.js'))
assert.ok(worker.includes("startsWith('/api/')"))

console.log('Socratic Kernel smoke checks passed.')
